### ISSUE TITLE
Send dropping messages over 438 characters

### ISSUE THREAD

**Issue by jseely** [vcabbage/amqp#54] opened 2018-03-20 21:33 UTC
I have an application that uses the Send method to send a json encoded byte array and it seems to be dropping messages when the message data is over 438 bytes. Is there some flag I need to set for longer strings?

I'm using Azure Event Hubs (which shows no messages received when I only send messages over 438 bytes)

```
serializedEvent, err := eh.codec.Encode(eh.index, &event.Content)
  if err != nil {
    if !event.Guaranteed() {
      return false
    }

    logp.Critical("Unable to encode event: %v", err)
    return false
  }

  session, err := eh.client.NewSession()
  if err != nil {
    logp.Critical("Creating AMQP session: %v", err)
    return false
  }

  sender, err := session.NewSender(amqp.LinkTargetAddress("/" + eh.queue))
  if err != nil {
    logp.Critical("Creating sender link: %v", err)
    return false
  }

  //message := amqp.NewMessage(serializedEvent)
  message := &amqp.Message{
    Data: [][]byte{serializedEvent[:438], serializedEvent[438:]},
  }
  logp.Info("Sending message: %v", message)
  err = sender.Send(context.Background(), message)
  defer sender.Close()
  if err != nil {
    logp.Critical("Sending message: %v", err)
    return false
  }
  return true
```

**Comment by vcabbage** [comment] 2018-03-20 22:26
I can try to reproduce this later. It shouldn't be dropping the messages as far as I'm aware.

Is the above a reproduction? I'm not sure Event Hubs will work with `Data: [][]byte{serializedEvent[:438], serializedEvent[438:]}`. If I remember correctly, when I tried something similar with Service Bus only the first data payload was recognized, it seemed to ignore the second data payload.

**Comment by devigned** [comment] 2018-03-22 16:31
Here's some debug output I've captured when sending a message over 438 bytes.
```
$ go test -v -timeout 100s -run 'TestIssue54_MessagesOver438Chars' -tags "integration debug"
=== RUN   TestIssue54_MessagesOver438Chars
=== RUN   TestIssue54_MessagesOver438Chars/issue54-messages-over-438-chars
TX: Begin{RemoteChannel: 0, NextOutgoingID: 0, IncomingWindow: 5000, OutgoingWindow: 4294967295, HandleMax: 0, OfferedCapabilities: [], DesiredCapabilities: [], Properties: map[]}
RX: Begin{RemoteChannel: 0, NextOutgoingID: 1, IncomingWindow: 5000, OutgoingWindow: 5000, HandleMax: 255, OfferedCapabilities: [], DesiredCapabilities: [], Properties: map[]}
TX: Attach{Name: AGvQHzLfvPCkPdMrAnfyOlkovNrauyoMBDDZgVUM, Handle: 0, Role: Sender, SenderSettleMode: <nil>, ReceiverSettleMode: second, Source: <nil>, Target: source{Address: integration-issue54-11059684649119627575/Partitions/0, Durable: 0, ExpiryPolicy: , Timeout: 0, Dynamic: false, DynamicNodeProperties: map[], Capabilities: []}, Unsettled: map[], IncompleteUnsettled: false, InitialDeliveryCount: 0, MaxMessageSize: 9223372036854775807, OfferedCapabilities: [], DesiredCapabilities: [], Properties: map[]}
RX(Session): Attach{Name: AGvQHzLfvPCkPdMrAnfyOlkovNrauyoMBDDZgVUM, Handle: 0, Role: Receiver, SenderSettleMode: <nil>, ReceiverSettleMode: second, Source: <nil>, Target: source{Address: integration-issue54-11059684649119627575/Partitions/0, Durable: 0, ExpiryPolicy: session-end, Timeout: 0, Dynamic: false, DynamicNodeProperties: map[], Capabilities: []}, Unsettled: map[], IncompleteUnsettled: false, InitialDeliveryCount: 0, MaxMessageSize: 262144, OfferedCapabilities: [], DesiredCapabilities: [], Properties: map[]}
RX(Session): Flow{NextIncomingID: 0, IncomingWindow: 5000, NextOutgoingID: 1, OutgoingWindow: 5000, Handle: 0, DeliveryCount: 0, LinkCredit: 1000, Available: 0, Drain: false, Echo: false, Properties: map[]}
RX(Session): Detach{Handle: 0, Closed: true, Error: *Error{Condition: amqp:not-allowed, Description: , Info: map[]}}
RX: Detach{Handle: 0, Closed: true, Error: *Error{Condition: amqp:not-allowed, Description: , Info: map[]}}
TX(Session): Detach{Handle: 0, Closed: true, Error: *Error(nil)}
--- FAIL: TestIssue54_MessagesOver438Chars (53.89s)
	integration_test.go:681: Creating hub integration-issue54-11059684649119627575
    --- FAIL: TestIssue54_MessagesOver438Chars/issue54-messages-over-438-chars (2.37s)
    	integration_test.go:431: Expected nil, got error link detached, reason: *Error{Condition: amqp:not-allowed, Description: , Info: map[]}
FAIL
exit status 1
FAIL	pack.ag/amqp	53.916s
```

Here's the test I'm running as well:
```go
func TestIssue54_MessagesOver438Chars(t *testing.T) {
	hubName, _, cleanup := newTestHub(t, "issue54")
	defer cleanup()

	label := "issue54-messages-over-438-chars"
	t.Run(label, func(t *testing.T) {
		checkLeaks := leaktest.CheckTimeout(t, 60*time.Second)

		// Create client
		client := newEHClient(t, "issue54")
		defer client.Close()

		// Open a session
		session, err := client.NewSession()
		if err != nil {
			t.Fatal(err)
		}

		senderPartitionPath := hubName + "/Partitions/0"
		// Create a sender
		sender, err := session.NewSender(
			amqp.LinkTargetAddress(senderPartitionPath),
			amqp.LinkReceiverSettle(amqp.ModeSecond),
		)
		if err != nil {
			t.Fatalf("%+v\n", err)
		}

		data := make([]byte, 439)
		rand.Read(data)
		err = sender.Send(context.Background(), amqp.NewMessage(data))
		if err != nil {
			t.Fatal("Expected nil, got error", err)
		}

		var wg sync.WaitGroup
		wg.Add(1)
		var receiveErr error
		go func() {
			defer wg.Done()

			// Create a receiver
			receiverPartitionPath := hubName + "/ConsumerGroups/$Default/Partitions/0"
			receiver, err := session.NewReceiver(
				amqp.LinkSourceAddress(receiverPartitionPath),
				amqp.LinkCredit(10),
				amqp.LinkBatching(false),
			)
			if err != nil {
				receiveErr = err
				return
			}
			defer receiver.Close()
			ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
			msg, err := receiver.Receive(ctx)
			cancel()
			if err != nil {
				receiveErr = fmt.Errorf("Error after receives: %+v", err)
				return
			}

			if !bytes.Equal([]byte(data), msg.GetData()) {
				receiveErr = fmt.Errorf("Expected received message to be %v, but it was %v", string(data), string(msg.GetData()))
			}
		}()

		wg.Wait()
		if receiveErr != nil {
			t.Fatal("Receive error:", receiveErr)
		}

		client.Close() // close before leak check

		checkLeaks()
	})
}
```

**Comment by devigned** [comment] 2018-03-22 16:58
After checking the send buffer for a message of 439 bytes, the first frame is sent with 446 bytes and the second is attempted to be sent with 1 byte. So, does it make sense that the issue is in how send framing is being handled?

**Comment by jseely** [comment] 2018-03-22 21:06
@vcabbage yes that is the repro, if I remember correctly though I had also tried putting the whole payload in the first data payload and it still wasn't being received in EH.

**Comment by devigned** [comment] 2018-03-22 21:40
With some help from the EH team I was able to deduce that the delivery-id is being incremented between the first frame and the second. This causes the entire message to fail. The delivery-id needs to be the same or omitted, but is currently being incremented and set if nil.

**Comment by vcabbage** [comment] 2018-03-24 02:20
Sorry for the delayed response, I was sick for a couple days.

Thanks for reporting this @jseely. 

Thanks for digging in to it @devigned, it probably would have taken me a while to find the cause.

I've opened a PR with a fix. I'm not going to merge it immediately as I may want to make some changes, but I should have it merged by the end of the weekend.

**Comment by devigned** [comment] 2018-03-24 17:08
No worries. Hope you’re feeling better.

**Closed** 2018-03-24 22:46 UTC
